{{- if .Values.controller_export_metrics.enable }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/auth-realm: Authentication Required
    nginx.ingress.kubernetes.io/auth-secret: basic-auth
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/configuration-snippet: |
      if ($request_uri ~ '^/metrics$') {
        add_header Cache-Control "no-store, no-cache";
      }
{{- if .Values.ip_filtration.enable }}
    nginx.ingress.kubernetes.io/server-snippet: |
      if ($grant_access = no) {rewrite ^ /access_error;}
{{- end }}
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  name: ingress-nginx-metrics
  namespace: {{ .Release.Namespace }}
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.controller_export_metrics.host }}
    http:
      paths:
      - backend:
          service:
            name: {{ include "ingress-nginx.controller.fullname" . }}-metrics
            port:
              number: {{ .Values.controller.metrics.service.servicePort }}
        path: /metrics
        pathType: ImplementationSpecific
{{- end }}